### ISSUE TITLE
DNS probe KProbeCtxRestoreFailure

### ISSUE THREAD

**Issue by dstruck** [0xrawsec/kunai#13]
Hello,

Getting the following errors:

```
[2023-12-05T18:49:47Z ERROR kunai_ebpf::probes::dns] KProbeCtxRestoreFailure
[2023-12-05T19:01:47Z ERROR kunai_ebpf::probes::dns] KProbeCtxRestoreFailure
[2023-12-05T19:13:47Z ERROR kunai_ebpf::probes::dns] KProbeCtxRestoreFailure
```

Using the latest binary (v0.1.0).

What might be the reason?

**Comment by qjerome** [comment]
Hi @dstruck,

The dns_query event management is quite complex, due to the number of ways Linux has to send/receive network data.
So it is necessary to have both hook on function entry points and on function exit.
This error happens only because hook on exit cannot restore information from function entry.
The symptom of this error, is not clearly identified yet but might be various ! 
However, it is not because it is the DNS probe returning this error that it necessarily impacts the events dns_query events. Indeed to generate dns_query events we need to hook many networking APIs, it is just the parsing of the data that tells if it is looking like DNS data or not. 
All this to say that, if dns_query events are not missing, this error is not really an issue as it might happen only under some conditions not impacting the generation of the concerned event. 
Would you please tell me if you notice missing dns_query events ? In which case I would escalate the priority of this issue.

Thanks,

**Comment by dstruck** [comment]
Hi @qjerome,

I have correlated the error timestamps with the event timestamps. I see no *connect* nor *dns_query* events within a 1 second range when the *KProbeCtxRestoreFailure* happens.

**Comment by qjerome** [comment]
Hi @dstruck,

Thanks for your input.
If you do expect an event that you don't see, there is definitely an issue !
Do you manage to reproduce the issue in a simple manner (using common Linux utilities like dig, curl ...) ?
If yes, please complete the following items.

Distribution:

Kernel (uname -r):

Steps to reproduce the issue:

**Comment by dstruck** [comment]
Unfortunately I don't know which conditions/processes trigger this error. Neither does `tcpdump -i any port 53 -n` show any connections to port 53 during the occurrence of those errors.

Would it be possible to print more debug output for this error?

**Comment by qjerome** [comment]
Ok, so it is probably what meant in my first reply. The issue probably does not happen for DNS traffic ! It very likely happens for another protocol, that is not relevant to the DNS probe.

The importance here, is not really the error message as I made the choice not to hide errors. Let's say errors are there to help if something unexpected happens. The importance is more if you are missing an event you are expecting to see.
For instance in this particular case, if you are missing a DNS query you are expecting to see, there is a big issue and error message can help. If you don't miss any event, even if there is an error from time to time, it is not a big deal. Maybe I should display those as warnings if it is too alarming (you are not the first one to tell me about those)!

No, there is not much advanced debug output as it is not easy to implement in BPF. This is something on my ToDo list but it will take several days (maybe weeks) to implement properly.

**Comment by dstruck** [comment]
I see. Thank you for the explanation :+1: 

Flagging those errors as warning would probably be more accurate. Error means, at least for me, that the system is not working properly.

**Comment by qjerome** [comment]
Yes, for the moment everything going wrong is an error. But definitely some things should be turned into warnings.
I opened an issue to track this out #16
